name: ESLint Checks

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - '**/feature-*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run lint
